flags: {}
nix:
  path: []
  nix-shell-options: []
  packages: []
  enable: false
  pure: true
packages:
- '.'
extra-deps: 
- aeson-extra-0.3.0.0
- aeson-compat-0.3.0.0
- time-parsers-0.1.0.0
resolver: lts-3.1
